---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: sihemkh/app-pfe:v2
        name: app
        env:
        - name: APP_DATABASE_HOST
          value: mysqli
        - name: APP_DATABASE_PORT
          value: "3306"
        - name: MYSQL_DATABASE_NAME
          value: testing
        - name: APP_DATABASE_USER
          value: user
        - name: APP_DATABASE_PASSWORD
          value: "12345"
        ports:
        - containerPort: 80
          name: app
